### ISSUE TITLE
Request: add Bamboo table by default

### ISSUE THREAD

**Issue by DaeTheDerg** [moonfather1/tetra_tables#1]
Hiya! not sure if this is an oversight, but every type of vanilla wood currently has an associated tetra table, except for bamboo wood added in 1.20.
it'd be great if this could be natively supported like the other woods!!

**Comment by moonfather1** [comment]
yes it was kinda of an oversight at first...

but then, when workshop (another mod of mine) added automatic support for all wood types and included support for tetra tables along with its own blocks, not only do you have a workaround but the very idea of going beyond it is questionable. 

is there someone who wants bamboo tetra table but doesn't want a selection of pretty bamboo toolracks that match that table? and if there is, what is wrong with them?

**Comment by DaeTheDerg** [comment]
Yeees there is, and I'm one of them
I want the tetra table variants without all the bloat from workshop, and I already have variant wood crafting tables from my own kubejs recipes.

Reasons I'm not installing workshop:

· Keeping the mod count down (not everyone has a great computer, some of my friends use silly windows office laptops, & every little helps - this is the main reason for using kubejs for a lot of recipes in the first place)
· Redundancies - most of the things that workshop adds I already have through other mods, and I find duplicates annoying
· I don't *need* infinite wood types because I only have the vanilla ones in the first place 

If you really don't want to add bamboo tables for whatever  reason, maybe you could try using [Dynamic Asset Generator](https://modrinth.com/mod/dynamic_asset_generator) instead! I believe this is what [Excavated Variants](https://modrinth.com/mod/excavated_variants) uses and it doesn't add any unrelated content.

**Comment by moonfather1** [comment]
i'll add bamboo tables.

whether i'm right about this workaround and whether you're right about not liking it - doesn't matter. this is a standalone mod and omission of bamboo table is something that i should fix. i'll upload a new version; you'll get a notification when i close this issue.

**Comment by DaeTheDerg** [comment]
Great! Thanks so much 💜

**Comment by moonfather1** [comment]
done. i don't like the look, but it is how it is... bamboo gives you multiple options on how a block would look but i couldn't get the look that i like.

**Comment by DaeTheDerg** [comment]
That's great thanks
unfortunately the project fails to build when I try to compile it, I think it's because I don't have the handsome adventurer source files but I don't know how I would go about importing them myself.

This is the error I get:
```
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find blank:workshop_for_handsome_adventurer--mc1.20.1-:1.14.7_mapped_official_1.20.1.
     Searched in the following locations:
       - file:/home/dae/.gradle/caches/forge_gradle/bundled_deobf_repo/blank/workshop_for_handsome_adventurer--mc1.20.1-/1.14.7_mapped_official_1.20.1/workshop_for_handsome_adventurer--mc1.20.1--1.14.7_mapped_official_1.20.1.pom
       - file:/home/dae/.gradle/caches/forge_gradle/bundled_deobf_repo/blank/workshop_for_handsome_adventurer--mc1.20.1-/1.14.7_mapped_official_1.20.1/workshop_for_handsome_adventurer--mc1.20.1--1.14.7_mapped_official_1.20.1.jar
     Required by:
         project :
   > Could not find curse.maven:tetra-289712:4857842_mapped_official_1.20.1.
     Searched in the following locations:
       - file:/home/dae/.gradle/caches/forge_gradle/bundled_deobf_repo/curse/maven/tetra-289712/4857842_mapped_official_1.20.1/tetra-289712-4857842_mapped_official_1.20.1.pom
       - file:/home/dae/.gradle/caches/forge_gradle/bundled_deobf_repo/curse/maven/tetra-289712/4857842_mapped_official_1.20.1/tetra-289712-4857842_mapped_official_1.20.1.jar
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
```

if it works for you though, would you be able to update the modrinth release?

**Comment by moonfather1** [comment]
you could have gone to discord for this, people sometimes miss things in closed issues.
and i would not want to not help a fellow developer in need.

try these
`runtimeOnly fg.deobf("curse.maven:tetra-tables-looking-neat-954341:5225383")`
`runtimeOnly fg.deobf("curse.maven:workshop-for-handsome-adventurer-875843:5043031")`
in dependencies, and 
```
maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
```
in repositories.
